theme: jekyll-theme-minimal
title: Stars or Storyline
description: How Actor Fame and Sentiment Trajectories Shape a Movie's Critical Success
show_downloads: false
navigation:
  - title: Home
    url: /ada-template-website/
  - title: Data Analysis
    url: /ada-template-website/data-analysis
  - title: Sentiment Analysis
    url: /ada-template-website/sentiment-analysis
  - title: Network Analysis
    url: /ada-template-website/network-analysis
  - title: Results
    url: /ada-template-website/results