remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Stars or Storyline
description: How Actor Fame and Sentiment Trajectories Shape a Movie's Critical Success
baseurl: "/ada-template-website"
url: "https://pierrelts.github.io"
navigation:
  - title: Home
    url: /home
  - title: Data Analysis
    url: /data-analysis
  - title: Sentiment Analysis
    url: /sentiment-analysis
  - title: Network Analysis
    url: /network-analysis
  - title: Results
    url: /results
github:
  is_project_page: false

# Dark theme settings
colors:
  background: "#1e1e1e"
  text: "#e0e0e0"
  heading: "#ffffff"
  link: "#39c"